<?php
return array(
    'default' => array(
        'body'       => '#ffffff',
        'text'       => '#000000',
        'link-text'  => '#000000',
        'link-hover' => '#222222',
        'line'       => '#eeeeee',
        'main'       => array(
            'default'    => '#ffffff',
            'text'       => '#000000',
            'hover'      => '#f5f5f5',
            'text-hover' => '#131313',
        ),
        'sub'        => array(
            'default'    => '#f8f8f8',
            'text'       => '#000000',
            'hover'      => '#f5f5f5',
            'text-hover' => '#131313',
        ),
        'action'     => array(
            'default'    => '#dd0000',
            'text'       => '#ffffff',
            'hover'      => '#be0000',
            'text-hover' => '#ffffff',
        ),
        'info'       => array(
            'default'    => '#007ddd',
            'text'       => '#ffffff',
            'hover'      => '#0171c7',
            'text-hover' => '#ffffff',
        ),
        'success'    => array(
            'default'    => '#34dd00',
            'text'       => '#ffffff',
            'hover'      => '#51e724',
            'text-hover' => '#ffffff',
        ),
    ),
    'blue' => array(
        'body'       => '#ffffff',
        'text'       => '#000000',
        'link-text'  => '#000000',
        'link-hover' => '#222222',
        'line'       => '#eeeeee',
        'main'       => array(
            'default'    => '#ffffff',
            'text'       => '#000000',
            'hover'      => '#f5f5f5',
            'text-hover' => '#131313',
        ),
        'sub'        => array(
            'default'    => '#ddf0ff',
            'text'       => '#191c1e',
            'hover'      => '#ebf6fe',
            'text-hover' => '#212629',
        ),
        'action'     => array(
            'default'    => '#dd0000',
            'text'       => '#ffffff',
            'hover'      => '#be0000',
            'text-hover' => '#ffffff',
        ),
        'info'       => array(
            'default'    => '#007ddd',
            'text'       => '#ffffff',
            'hover'      => '#0171c7',
            'text-hover' => '#ffffff',
        ),
        'success'    => array(
            'default'    => '#34dd00',
            'text'       => '#ffffff',
            'hover'      => '#51e724',
            'text-hover' => '#ffffff',
        ),
    ),
    'green' => array(
        'body'       => '#ffffff',
        'text'       => '#000000',
        'link-text'  => '#000000',
        'link-hover' => '#222222',
        'line'       => '#eeeeee',
        'main'       => array(
            'default'    => '#ffffff',
            'text'       => '#000000',
            'hover'      => '#f5f5f5',
            'text-hover' => '#131313',
        ),
        'sub'        => array(
            'default'    => '#eafff1',
            'text'       => '#201b14',
            'hover'      => '#f1fef5',
            'text-hover' => '#2e271d',
        ),
        'action'     => array(
            'default'    => '#dd0000',
            'text'       => '#ffffff',
            'hover'      => '#be0000',
            'text-hover' => '#ffffff',
        ),
        'info'       => array(
            'default'    => '#007ddd',
            'text'       => '#ffffff',
            'hover'      => '#0171c7',
            'text-hover' => '#ffffff',
        ),
        'success'    => array(
            'default'    => '#34dd00',
            'text'       => '#ffffff',
            'hover'      => '#51e724',
            'text-hover' => '#ffffff',
        ),
    ),
);