<?php
$array_metabox_section[] = array(
  'name'   => 'freelayout-sort','title'  => '並び替え',
  'fields' => array(
      array('id' => 'sort','type'   => 'group','title'  => 'セクションコンテンツ',
          'fields' => array(
              array('id'    => 'title','type'  => 'text','title' => 'セクションラベル(サイト上非表示)'),
              array('id'    => 'section-type','type'  => 'select','title' => 'セクションタイプ',
                  'options' => array(
                      'heroimage-1' => 'ヒーローイメージ 1',
                      'heroimage-2' => 'ヒーローイメージ 2',
                      'heroimage-3' => 'ヒーローイメージ 3',
                      'heroimage-4' => 'ヒーローイメージ 4',
                      'heroimage-5' => 'ヒーローイメージ 5',
                      'columncontents-1' => 'カラムコンテンツ 1',
                      'columncontents-2' => 'カラムコンテンツ 2',
                      'columncontents-3' => 'カラムコンテンツ 3',
                      'columncontents-4' => 'カラムコンテンツ 4',
                      'columncontents-5' => 'カラムコンテンツ 5',
                      'columncontents-6' => 'カラムコンテンツ 6',
                      'columncontents-7' => 'カラムコンテンツ 7',
                      'columncontents-8' => 'カラムコンテンツ 8',
                      'columncontents-9' => 'カラムコンテンツ 9',
                      'columncontents-10' => 'カラムコンテンツ 10',
                      'loop-1' => 'ループ 1',
                      'loop-2' => 'ループ 2',
                      'loop-3' => 'ループ 3',
                      'loop-4' => 'ループ 4',
                      'loop-5' => 'ループ 5',
                      'loop-6' => 'ループ 6',
                      'loop-7' => 'ループ 7',
                      'loop-8' => 'ループ 8',
                      'loop-9' => 'ループ 9',
                      'loop-10' => 'ループ 10',
                      'form-1' => 'フォーム 1',
                      'form-2' => 'フォーム 2',
                      'form-3' => 'フォーム 3',
                      'form-4' => 'フォーム 4',
                      'form-5' => 'フォーム 5',
                  ),
              ),
              array('id' => 'section-class','type'  => 'text','title' => 'class'),
              array('id' => 'section-id','type'  => 'text','title' => 'id'),
          )
      ),
  ),
);