<?php
$array_metabox_section[] = array(
  'name' => 'config-order','title'  => 'コンテンツ配置','fields' => array(
      array('id' => 'contents','type'   => 'group','title'  => 'コンテンツ',
          'fields' => array(
              array('id'    => 'title','type'  => 'text','title' => 'ラベル'),
              array('id'    => 'type','type'  => 'select','title' => 'コンテンツ',
                  'options' => array(
                      'mainvisual' => 'メインビジュアル',
                      'title1' => 'タイトル①',
                      'title2' => 'タイトル②',
                      'title3' => 'タイトル③',
                      'cta1' => 'CTA①',
                      'cta2' => 'CTA②',
                      'cta3' => 'CTA③',
                      'contents-fullscreen1' => 'コンテンツ(フルスクリーン)①',
                      'contents-fullscreen2' => 'コンテンツ(フルスクリーン)②',
                      'contents-fullscreen3' => 'コンテンツ(フルスクリーン)③',
                      'contents-fullscreen4' => 'コンテンツ(フルスクリーン)④',
                      'contents-fullscreen5' => 'コンテンツ(フルスクリーン)⑤',
                      'contents-column1' => 'コンテンツ(カラム)①',
                      'contents-column2' => 'コンテンツ(カラム)②',
                      'contents-column3' => 'コンテンツ(カラム)③',
                      'contents-column4' => 'コンテンツ(カラム)④',
                      'contents-column5' => 'コンテンツ(カラム)⑤',
                      'contents-detail1' => 'コンテンツ(詳細)①',
                      'contents-detail2' => 'コンテンツ(詳細)②',
                      'contents-detail3' => 'コンテンツ(詳細)③',
                      'loop-column1' => 'ループ(カラム)①',
                      'loop-column2' => 'ループ(カラム)②',
                      'loop-column3' => 'ループ(カラム)③',
                      'flow1' => 'フロー①',
                      'flow2' => 'フロー②',
                      'flow3' => 'フロー③',
                      'form1' => 'フォーム①',
                      'form2' => 'フォーム②',
                      'form3' => 'フォーム③',
                      'table' => '表',
                      'table-price' => '料金表',
                      'code1' => 'コード①',
                      'code2' => 'コード②',
                      'code3' => 'コード③',
                  ),
              ),
              array('id'    => 'class','type'  => 'text','title' => 'クラス'),
              array('id'    => 'section-id','type'  => 'text','title' => 'ID'),
          )
      ),
  ),
);