<?php
return array(
    'default' => array(
        'body'       => '#ffffff',
        'text'       => '#000000',
        'link-text'  => '#000000',
        'link-hover' => '#222222',
        'line'       => '#eeeeee',
        'main'       => array(
            'default'    => '#ffffff',
            'text'       => '#000000',
            'hover'      => '#f5f5f5',
            'text-hover' => '#131313',
        ),
        'sub'        => array(
            'default'    => '#f8f8f8',
            'text'       => '#000000',
            'hover'      => '#f5f5f5',
            'text-hover' => '#131313',
        ),
        'action'     => array(
            'default'    => '#dd0000',
            'text'       => '#ffffff',
            'hover'      => '#be0000',
            'text-hover' => '#ffffff',
        ),
        'info'       => array(
            'default'    => '#007ddd',
            'text'       => '#ffffff',
            'hover'      => '#0171c7',
            'text-hover' => '#ffffff',
        ),
        'success'    => array(
            'default'    => '#34dd00',
            'text'       => '#ffffff',
            'hover'      => '#51e724',
            'text-hover' => '#ffffff',
        ),
    ),
    'blue' => array(
        'body'       => '#ffffff',
        'text'       => '#000000',
        'link-text'  => '#000000',
        'link-hover' => '#222222',
        'line'       => '#eeeeee',
        'main'       => array(
            'default'    => '#ffffff',
            'text'       => '#000000',
            'hover'      => '#f5f5f5',
            'text-hover' => '#131313',
        ),
        'sub'        => array(
            'default'    => '#ddf0ff',
            'text'       => '#191c1e',
            'hover'      => '#ebf6fe',
            'text-hover' => '#212629',
        ),
        'action'     => array(
            'default'    => '#dd0000',
            'text'       => '#ffffff',
            'hover'      => '#be0000',
            'text-hover' => '#ffffff',
        ),
        'info'       => array(
            'default'    => '#007ddd',
            'text'       => '#ffffff',
            'hover'      => '#0171c7',
            'text-hover' => '#ffffff',
        ),
        'success'    => array(
            'default'    => '#34dd00',
            'text'       => '#ffffff',
            'hover'      => '#51e724',
            'text-hover' => '#ffffff',
        ),
    ),
    'green' => array(
        'body'       => '#ffffff',
        'text'       => '#000000',
        'link-text'  => '#000000',
        'link-hover' => '#222222',
        'line'       => '#eeeeee',
        'main'       => array(
            'default'    => '#ffffff',
            'text'       => '#000000',
            'hover'      => '#f5f5f5',
            'text-hover' => '#131313',
        ),
        'sub'        => array(
            'default'    => '#eafff1',
            'text'       => '#201b14',
            'hover'      => '#f1fef5',
            'text-hover' => '#2e271d',
        ),
        'action'     => array(
            'default'    => '#dd0000',
            'text'       => '#ffffff',
            'hover'      => '#be0000',
            'text-hover' => '#ffffff',
        ),
        'info'       => array(
            'default'    => '#007ddd',
            'text'       => '#ffffff',
            'hover'      => '#0171c7',
            'text-hover' => '#ffffff',
        ),
        'success'    => array(
            'default'    => '#34dd00',
            'text'       => '#ffffff',
            'hover'      => '#51e724',
            'text-hover' => '#ffffff',
        ),
    ),
    'red' => array(
        'body'       => '#ffffff',
        'text'       => '#000000',
        'link-text'  => '#000000',
        'link-hover' => '#222222',
        'line'       => '#eeeeee',
        'main'       => array(
            'default'    => '#ffffff',
            'text'       => '#000000',
            'hover'      => '#f5f5f5',
            'text-hover' => '#131313',
        ),
        'sub'        => array(
            'default'    => '#ffeaea',
            'text'       => '#201414',
            'hover'      => '#fef1f1',
            'text-hover' => '#2e1d1d',
        ),
        'action'     => array(
            'default'    => '#dd0000',
            'text'       => '#ffffff',
            'hover'      => '#be0000',
            'text-hover' => '#ffffff',
        ),
        'info'       => array(
            'default'    => '#007ddd',
            'text'       => '#ffffff',
            'hover'      => '#0171c7',
            'text-hover' => '#ffffff',
        ),
        'success'    => array(
            'default'    => '#34dd00',
            'text'       => '#ffffff',
            'hover'      => '#51e724',
            'text-hover' => '#ffffff',
        ),
    ),
    'yellow' => array(
        'body'       => '#ffffff',
        'text'       => '#000000',
        'link-text'  => '#000000',
        'link-hover' => '#222222',
        'line'       => '#eeeeee',
        'main'       => array(
            'default'    => '#ffffff',
            'text'       => '#000000',
            'hover'      => '#f5f5f5',
            'text-hover' => '#131313',
        ),
        'sub'        => array(
            'default'    => '#fcffea',
            'text'       => '#201f14',
            'hover'      => '#fdfef1',
            'text-hover' => '#2e2c1d',
        ),
        'action'     => array(
            'default'    => '#dd0000',
            'text'       => '#ffffff',
            'hover'      => '#be0000',
            'text-hover' => '#ffffff',
        ),
        'info'       => array(
            'default'    => '#007ddd',
            'text'       => '#ffffff',
            'hover'      => '#0171c7',
            'text-hover' => '#ffffff',
        ),
        'success'    => array(
            'default'    => '#34dd00',
            'text'       => '#ffffff',
            'hover'      => '#51e724',
            'text-hover' => '#ffffff',
        ),
    ),
    'purple' => array(
        'body'       => '#ffffff',
        'text'       => '#000000',
        'link-text'  => '#000000',
        'link-hover' => '#222222',
        'line'       => '#eeeeee',
        'main'       => array(
            'default'    => '#ffffff',
            'text'       => '#000000',
            'hover'      => '#f5f5f5',
            'text-hover' => '#131313',
        ),
        'sub'        => array(
            'default'    => '#f8eaff',
            'text'       => '#1d1420',
            'hover'      => '#faf1fe',
            'text-hover' => '#281d2e',
        ),
        'action'     => array(
            'default'    => '#dd0000',
            'text'       => '#ffffff',
            'hover'      => '#be0000',
            'text-hover' => '#ffffff',
        ),
        'info'       => array(
            'default'    => '#007ddd',
            'text'       => '#ffffff',
            'hover'      => '#0171c7',
            'text-hover' => '#ffffff',
        ),
        'success'    => array(
            'default'    => '#34dd00',
            'text'       => '#ffffff',
            'hover'      => '#51e724',
            'text-hover' => '#ffffff',
        ),
    ),
    'pink' => array(
        'body'       => '#ffffff',
        'text'       => '#000000',
        'link-text'  => '#000000',
        'link-hover' => '#222222',
        'line'       => '#eeeeee',
        'main'       => array(
            'default'    => '#ffffff',
            'text'       => '#000000',
            'hover'      => '#f5f5f5',
            'text-hover' => '#131313',
        ),
        'sub'        => array(
            'default'    => '#ffeafd',
            'text'       => '#20141d',
            'hover'      => '#fef1fb',
            'text-hover' => '#2e1d2e',
        ),
        'action'     => array(
            'default'    => '#dd0000',
            'text'       => '#ffffff',
            'hover'      => '#be0000',
            'text-hover' => '#ffffff',
        ),
        'info'       => array(
            'default'    => '#007ddd',
            'text'       => '#ffffff',
            'hover'      => '#0171c7',
            'text-hover' => '#ffffff',
        ),
        'success'    => array(
            'default'    => '#34dd00',
            'text'       => '#ffffff',
            'hover'      => '#51e724',
            'text-hover' => '#ffffff',
        ),
    ),
    'orange' => array(
        'body'       => '#ffffff',
        'text'       => '#000000',
        'link-text'  => '#000000',
        'link-hover' => '#222222',
        'line'       => '#eeeeee',
        'main'       => array(
            'default'    => '#ffffff',
            'text'       => '#000000',
            'hover'      => '#f5f5f5',
            'text-hover' => '#131313',
        ),
        'sub'        => array(
            'default'    => '#fff4ea',
            'text'       => '#201a14',
            'hover'      => '#fef7f1',
            'text-hover' => '#2e271d',
        ),
        'action'     => array(
            'default'    => '#dd0000',
            'text'       => '#ffffff',
            'hover'      => '#be0000',
            'text-hover' => '#ffffff',
        ),
        'info'       => array(
            'default'    => '#007ddd',
            'text'       => '#ffffff',
            'hover'      => '#0171c7',
            'text-hover' => '#ffffff',
        ),
        'success'    => array(
            'default'    => '#34dd00',
            'text'       => '#ffffff',
            'hover'      => '#51e724',
            'text-hover' => '#ffffff',
        ),
    ),
    'lightblue' => array(
        'body'       => '#ffffff',
        'text'       => '#000000',
        'link-text'  => '#000000',
        'link-hover' => '#222222',
        'line'       => '#eeeeee',
        'main'       => array(
            'default'    => '#ffffff',
            'text'       => '#000000',
            'hover'      => '#f5f5f5',
            'text-hover' => '#131313',
        ),
        'sub'        => array(
            'default'    => '#eafeff',
            'text'       => '#141f20',
            'hover'      => '#f1fefe',
            'text-hover' => '#1d2c2e',
        ),
        'action'     => array(
            'default'    => '#dd0000',
            'text'       => '#ffffff',
            'hover'      => '#be0000',
            'text-hover' => '#ffffff',
        ),
        'info'       => array(
            'default'    => '#007ddd',
            'text'       => '#ffffff',
            'hover'      => '#0171c7',
            'text-hover' => '#ffffff',
        ),
        'success'    => array(
            'default'    => '#34dd00',
            'text'       => '#ffffff',
            'hover'      => '#51e724',
            'text-hover' => '#ffffff',
        ),
    ),
);